var annotated_dup =
[
    [ "Lib433Mhz", "class_lib433_mhz.html", "class_lib433_mhz" ],
    [ "LibAff1637", "class_lib_aff1637.html", "class_lib_aff1637" ],
    [ "LibCan2515", "class_lib_can2515.html", "class_lib_can2515" ],
    [ "LibCanProtCommon", "class_lib_can_prot_common.html", "class_lib_can_prot_common" ],
    [ "LibCanProtRecv", "class_lib_can_prot_recv.html", "class_lib_can_prot_recv" ],
    [ "LibCanProtSend", "class_lib_can_prot_send.html", "class_lib_can_prot_send" ],
    [ "LibChrono", "class_lib_chrono.html", "class_lib_chrono" ],
    [ "LibClavier", "class_lib_clavier.html", "class_lib_clavier" ],
    [ "LibGpio", "class_lib_gpio.html", "class_lib_gpio" ],
    [ "LibGyroscope", "class_lib_gyroscope.html", "class_lib_gyroscope" ],
    [ "LibJoystick", "class_lib_joystick.html", "class_lib_joystick" ],
    [ "LibJumper", "class_lib_jumper.html", "class_lib_jumper" ],
    [ "LibMatrice", "class_lib_matrice.html", "class_lib_matrice" ],
    [ "LibMcp23008", "class_lib_mcp23008.html", "class_lib_mcp23008" ],
    [ "LibMoteur", "class_lib_moteur.html", "class_lib_moteur" ],
    [ "LibMoteurOmni", "class_lib_moteur_omni.html", "class_lib_moteur_omni" ],
    [ "LibMoteurS", "class_lib_moteur_s.html", "class_lib_moteur_s" ],
    [ "LibMultiTcs3472", "class_lib_multi_tcs3472.html", "class_lib_multi_tcs3472" ],
    [ "LibMuxI2c", "class_lib_mux_i2c.html", "class_lib_mux_i2c" ],
    [ "LibPami2025", "class_lib_pami2025.html", "class_lib_pami2025" ],
    [ "LibPami2026Basic", "class_lib_pami2026_basic.html", "class_lib_pami2026_basic" ],
    [ "LibPami2026Ninja", "class_lib_pami2026_ninja.html", "class_lib_pami2026_ninja" ],
    [ "LibPami2026NinjaOmni", "class_lib_pami2026_ninja_omni.html", "class_lib_pami2026_ninja_omni" ],
    [ "LibTcs3472", "class_lib_tcs3472.html", "class_lib_tcs3472" ],
    [ "LibUltrason", "class_lib_ultrason.html", "class_lib_ultrason" ],
    [ "LibVl53lox", "class_lib_vl53lox.html", "class_lib_vl53lox" ]
];